import type { Mentor } from "./matching";

export const SEED_MENTORS: Mentor[] = [
  {
    id: "mira-patel",
    name: "Mira Patel",
    headline: "Robotics engineer, India to U.S. graduate path",
    initials: "MP",
    domains: ["Robotics career", "AI/ML career", "Graduate school"],
    tags: ["robotics", "ros", "python", "graduate school", "projects", "india"],
    stages: ["School student", "College student", "Career switcher"],
    locations: ["India/IIT", "U.S. tech", "Remote global"],
    languages: ["English", "Hindi"],
    meetings: ["video", "in-person", "chat"],
    pricing: "community hours",
    trustScore: 92,
    reviewQuality: 88,
    responseRate: 94,
    verified: ["Email", "GitHub", "Portfolio"],
    payment: "Free community hours, then Stripe Payment Link",
    meeting: "Google Meet or public university space",
    availability: "Tue and Thu evenings",
    bio: "Recently completed an MS robotics path and now works on autonomy systems.",
  },
  {
    id: "daniel-kim",
    name: "Daniel Kim",
    headline: "B2B SaaS founder and product operator",
    initials: "DK",
    domains: ["Startup advice", "Product management", "Software engineering"],
    tags: ["b2b", "pricing", "gtm", "saas", "founder", "operator"],
    stages: ["Founder", "Senior operator", "Early career"],
    locations: ["U.S. tech", "Remote global"],
    languages: ["English"],
    meetings: ["video", "phone"],
    pricing: "paid",
    trustScore: 89,
    reviewQuality: 91,
    responseRate: 81,
    verified: ["Email", "Domain email", "LinkedIn"],
    payment: "Stripe Payment Link",
    meeting: "Zoom link after confirmation",
    availability: "Mon mornings and Fri afternoons",
    bio: "Built and sold a vertical SaaS company, now advises early B2B teams.",
  },
  {
    id: "ananya-rao",
    name: "Ananya Rao",
    headline: "AI career switch mentor and MLOps lead",
    initials: "AR",
    domains: ["AI/ML career", "Cloud/MLOps", "Data engineering"],
    tags: ["mlops", "career switch", "portfolio", "cloud", "interviews", "india"],
    stages: ["Career switcher", "Early career", "College student"],
    locations: ["India/IIT", "Remote global"],
    languages: ["English", "Telugu", "Hindi"],
    meetings: ["video", "chat"],
    pricing: "donation",
    trustScore: 86,
    reviewQuality: 84,
    responseRate: 89,
    verified: ["Email", "GitHub"],
    payment: "Donation link optional",
    meeting: "Google Meet",
    availability: "Weekends",
    bio: "Moved from backend engineering into applied ML and now leads model delivery.",
  },
  {
    id: "sofia-martinez",
    name: "Sofia Martinez",
    headline: "Product leader for developer tools",
    initials: "SM",
    domains: ["Product management", "Software engineering", "Startup advice"],
    tags: ["developer tools", "roadmap", "research", "stakeholders", "pm interviews"],
    stages: ["Early career", "Career switcher", "Senior operator"],
    locations: ["U.S. tech", "Remote global"],
    languages: ["English", "Spanish"],
    meetings: ["video", "phone"],
    pricing: "paid",
    trustScore: 83,
    reviewQuality: 87,
    responseRate: 77,
    verified: ["Email", "LinkedIn"],
    payment: "PayPal link",
    meeting: "Microsoft Teams",
    availability: "Wed afternoons",
    bio: "Coaches engineers moving into product and PMs working on technical products.",
  },
  {
    id: "ravi-menon",
    name: "Ravi Menon",
    headline: "Data engineering and cloud architecture advisor",
    initials: "RM",
    domains: ["Data engineering", "Cloud/MLOps", "Software engineering"],
    tags: ["data pipelines", "spark", "aws", "architecture", "platform"],
    stages: ["Early career", "Senior operator", "Career switcher"],
    locations: ["India/IIT", "Remote global"],
    languages: ["English", "Tamil", "Hindi"],
    meetings: ["video", "phone", "chat"],
    pricing: "free",
    trustScore: 78,
    reviewQuality: 80,
    responseRate: 91,
    verified: ["Email", "GitHub"],
    payment: "Free sessions only",
    meeting: "Decide after booking",
    availability: "Sat mornings",
    bio: "Helps engineers move from application work into data platform roles.",
  },
  {
    id: "grace-chen",
    name: "Grace Chen",
    headline: "Hiring manager for software engineering teams",
    initials: "GC",
    domains: ["Software engineering", "Graduate school", "AI/ML career"],
    tags: ["interviews", "resume", "hiring", "career ladder", "u.s. tech"],
    stages: ["College student", "Early career", "Career switcher"],
    locations: ["U.S. tech", "Remote global", "Local in-person"],
    languages: ["English"],
    meetings: ["video", "in-person"],
    pricing: "community hours",
    trustScore: 90,
    reviewQuality: 86,
    responseRate: 72,
    verified: ["Email", "Domain email", "LinkedIn"],
    payment: "Community hours or Wise link",
    meeting: "Video or public library meeting",
    availability: "Monthly office hours",
    bio: "Reviews career plans, interview readiness, and realistic hiring paths.",
  },
];
